Dev2
stepancar-web-programming/2022-fall-lab-portfolio-sypacheva-anastasiya-andreevna pull request #4
Opened 2022-11-27 11:07 UTC by Anastasias35

2022-11-27 15:38 UTC, KirpaDmitriy commented
Привет, Настя! Я был бы тебе очень благодарен, если бы ты перенесла изменения из ветки dev2 в ветку dev и добавила файл package.json, куда поместила бы ссылку на демо своего сайта с ключом "homepage"

2022-11-27 15:58 UTC, KirpaDmitriy commented
Ты можешь ветку слить с уже существующей dev (если там нет конфликтов) и сделать PR уже из ветки dev, содержащей все нужные изменения

2022-11-28 17:55 UTC, Nikesh16 commented on style.css
> +}
лучше убрать подчеркивание из строки меню

2022-11-28 17:55 UTC, Nikesh16 commented on index.html
> +    <title>Document</title>
Default title, can be changed to your name )

2022-12-17 03:57 UTC, stepancar commented on package.json
> +    "lint:fix": "eslint ./ --fix",
обратите внимание что эта команда дубль той, что в строке выше. Получается что вам придется поддерживать дубликат, что не хорошо, предлагаю исправить

2022-12-17 03:58 UTC, stepancar commented on package.json
> +  "main": "script.js",
мало вероятно что вы будете публиковать это как библиотеку, верно?

2022-12-17 03:58 UTC, stepancar commented on package.json
> +  "homepage": "https://anastasias35.github.io/anastasias35_web.github.io/",
404

2022-12-17 03:59 UTC, stepancar commented on script.js
> +  let indexBlock = 0;
не совсем понятно, для чего вам переменная за пределами цикла

2022-12-17 03:59 UTC, stepancar commented on script.js
> +  let indexBlock = 0;
не ясна идея с переменной за пределами цикла

2022-12-17 04:05 UTC, stepancar commented on script.js
> +    if (slides[i].style.display === 'block') {
Хороший паттерн при написании логики завязываться на состояния, которые под вашим контролем. вы же строите логико завязываясь на состояние представления. Дело в том, что не только ваш скрипт может владеть состоянием. и получается так что можно привести вашу программу в нерабочее состояние извне. Если вы оперируете внутренним состояние и просто мапите его на представление- вы получаете простоту в коде и уменьшаете вероятность поломки. предлагают исправить

2022-12-23 06:52 UTC, stepancar commented on package.json
> +    "lint:fix": "eslint ./ --fix",
@Anastasias35 , команда lint куда-то исчезла

2022-12-23 06:52 UTC, stepancar commented on package.json
> +  "main": "script.js",
@Anastasias35 жду исправления

2022-12-23 06:53 UTC, stepancar commented on package.json
> +    "url": "git+https://github.com/Anastasias35/web_project.git"
кажется что эта секция заполнена некорректно. при этом и смысла от нее нет, так как вы врядли будете публиковать этот проект в npm, верно?

2022-12-26 00:37 UTC, stepancar commented on package.json
> +    "stylelint:fix": "stylelint ./*css --fix"
@Anastasias35 , мы с вами общались по точно такой же проблеме выше. Однако кажется вы не поняли основной поинт.

как видите, коменды
"stylelint": "stylelint ./*css",
"stylelint:fix": "stylelint ./*css --fix"

отличаются лишь --fix, верно?
мой поинт в том, что если команда будет расширяться - есть возможность забыть отредактировать оба скрипта.

Если вы сделаете так

```
"stylelint": "stylelint ./*css",
"stylelint:fix": "npm run stylelint --fix"
```
то вам нужно будет поддержать только одну команду

2022-12-26 00:38 UTC, stepancar commented on script.js
> +}
Не отформатирован файл

2022-12-28 05:48 UTC, stepancar requested changes
не забудьте смержить ПР

2022-12-28 05:48 UTC, stepancar approved these changes

2022-12-28 05:49 UTC, stepancar requested changes
https://github.com/stepancar-web-programming/2022-fall-lab-portfolio-sypacheva-anastasiya-andreevna/pull/4/files#r1051306931

2022-12-28 15:41 UTC, merged